name: client
description: A Flutter login application with FastAPI integration
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  provider: ^6.1.1
  intl: ^0.18.1
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ml_bg.png"
  adaptive_icon_background: "#1A237E"
  adaptive_icon_foreground: "assets/images/ml_bg.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
